[package]
name = "asteroid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14.2"
bevy_rapier2d = "0.27.0"
rand = "0.8.4"
yaml-rust = "0.4.5"

[profile.dev]
opt-level = 1